// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/types";
import type * as prismicClient from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *footermenu → linkgroup*
 */
export interface FootermenuDocumentDataLinkgroupItem {
	/**
	 * label field in *footermenu → linkgroup*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footermenu.linkgroup[].label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	label: prismic.KeyTextField;
	
	/**
	 * link field in *footermenu → linkgroup*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footermenu.linkgroup[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;
}

/**
 * Item in *footermenu → socialmediagroup*
 */
export interface FootermenuDocumentDataSocialmediagroupItem {
	/**
	 * image field in *footermenu → socialmediagroup*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footermenu.socialmediagroup[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
	
	/**
	 * imagelink field in *footermenu → socialmediagroup*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footermenu.socialmediagroup[].imagelink
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	imagelink: prismic.LinkField;
}

/**
 * Content for footermenu documents
 */
interface FootermenuDocumentData {
	/**
	 * logo field in *footermenu*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footermenu.logo
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	logo: prismic.ImageField<never>;
	
	/**
	 * description field in *footermenu*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footermenu.description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;
	
	/**
	 * textrights field in *footermenu*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footermenu.textrights
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	textrights: prismic.RichTextField;
	
	/**
	 * linkgroup field in *footermenu*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footermenu.linkgroup[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	linkgroup: prismic.GroupField<Simplify<FootermenuDocumentDataLinkgroupItem>>;
	
	/**
	 * socialmediagroup field in *footermenu*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footermenu.socialmediagroup[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	socialmediagroup: prismic.GroupField<Simplify<FootermenuDocumentDataSocialmediagroupItem>>;
}

/**
 * footermenu document from Prismic
 *
 * - **API ID**: `footermenu`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FootermenuDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<FootermenuDocumentData>, "footermenu", Lang>;

type HomepageDocumentDataSlicesSlice = HeroSlice | IdeasSlice | CardListSlice | LogoListSlice | MetricsSlice | ServicesSlice | ProjectsSlice | ClientsSlice | StaffSlice | ContactSlice | ReviewsSlice

/**
 * Content for homepage documents
 */
interface HomepageDocumentData {
	/**
	 * seotitle field in *homepage*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.seotitle
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	seotitle: prismic.KeyTextField;
	
	/**
	 * seodescription field in *homepage*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.seodescription
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	seodescription: prismic.KeyTextField;
	
	/**
	 * Slice Zone field in *homepage*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>;
}

/**
 * homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<HomepageDocumentData>, "homepage", Lang>;

/**
 * Item in *menuTop → menuLinks*
 */
export interface MenutopDocumentDataMenulinksItem {
	/**
	 * label field in *menuTop → menuLinks*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: menutop.menulinks[].label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	label: prismic.KeyTextField;
	
	/**
	 * link field in *menuTop → menuLinks*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: menutop.menulinks[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;
}

/**
 * Content for menuTop documents
 */
interface MenutopDocumentData {
	/**
	 * logo field in *menuTop*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: menutop.logo
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	logo: prismic.ImageField<never>;
	
	/**
	 * title field in *menuTop*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: menutop.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.RichTextField;
	
	/**
	 * callToActionText field in *menuTop*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: menutop.calltoactiontext
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	calltoactiontext: prismic.RichTextField;
	
	/**
	 * callToActionURL field in *menuTop*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: menutop.calltoactionurl
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	calltoactionurl: prismic.LinkField;
	
	/**
	 * menuLinks field in *menuTop*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: menutop.menulinks[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	menulinks: prismic.GroupField<Simplify<MenutopDocumentDataMenulinksItem>>;
}

/**
 * menuTop document from Prismic
 *
 * - **API ID**: `menutop`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MenutopDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<MenutopDocumentData>, "menutop", Lang>;

type PageDocumentDataSlicesSlice = HeroSlice | IdeasSlice | CardListSlice | LogoListSlice | MetricsSlice | ServicesSlice | ProjectsSlice | ClientsSlice | ContactSlice | GraduateSlice | ReviewsSlice

/**
 * Content for page documents
 */
interface PageDocumentData {
	/**
	 * seotitle field in *page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.seotitle
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	seotitle: prismic.KeyTextField;
	
	/**
	 * seodescription field in *page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.seodescription
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	seodescription: prismic.KeyTextField;
	
	/**
	 * Slice Zone field in *page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<PageDocumentDataSlicesSlice>;
}

/**
 * page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes = FootermenuDocument | HomepageDocument | MenutopDocument | PageDocument;

/**
 * Primary content in *CardList → Default → Primary*
 */
export interface CardListSliceDefaultPrimary {
	/**
	 * title field in *CardList → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: card_list.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.RichTextField;
	
	/**
	 * description field in *CardList → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: card_list.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;
}

/**
 * Primary content in *CardList → Items*
 */
export interface CardListSliceDefaultItem {
	/**
	 * cardTitle field in *CardList → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: card_list.items[].cardTitle
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	cardTitle: prismic.RichTextField;
	
	/**
	 * cardDescription field in *CardList → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: card_list.items[].cardDescription
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	cardDescription: prismic.RichTextField;
	
	/**
	 * cardImage field in *CardList → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: card_list.items[].cardImage
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	cardImage: prismic.ImageField<never>;
}

/**
 * Default variation for CardList Slice
 *
 * - **API ID**: `default`
 * - **Description**: CardList
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardListSliceDefault = prismic.SharedSliceVariation<"default", Simplify<CardListSliceDefaultPrimary>, Simplify<CardListSliceDefaultItem>>;

/**
 * Slice variation for *CardList*
 */
type CardListSliceVariation = CardListSliceDefault

/**
 * CardList Shared Slice
 *
 * - **API ID**: `card_list`
 * - **Description**: CardList
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardListSlice = prismic.SharedSlice<"card_list", CardListSliceVariation>;

/**
 * Primary content in *Comparative → Default → Primary*
 */
export interface ClientsSliceDefaultPrimary {
	/**
	 * title field in *Comparative → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: clients.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;
	
	/**
	 * description field in *Comparative → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: clients.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	description: prismic.KeyTextField;
}

/**
 * Primary content in *Comparative → Items*
 */
export interface ClientsSliceDefaultItem {
	/**
	 * title field in *Comparative → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: clients.items[].title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.RichTextField;
	
	/**
	 * description field in *Comparative → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: clients.items[].description
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	description: prismic.KeyTextField;
	
	/**
	 * ico1 field in *Comparative → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: clients.items[].ico
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	ico: prismic.ImageField<never>;
	
	/**
	 * description1 field in *Comparative → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: clients.items[].description1
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	description1: prismic.KeyTextField;
	
	/**
	 * ico2 field in *Comparative → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: clients.items[].ico2
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	ico2: prismic.ImageField<never>;
	
	/**
	 * description2 field in *Comparative → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: clients.items[].description2
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	description2: prismic.KeyTextField;
	
	/**
	 * ico3 field in *Comparative → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: clients.items[].ico3
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	ico3: prismic.ImageField<never>;
	
	/**
	 * description3 field in *Comparative → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: clients.items[].description3
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	description3: prismic.KeyTextField;
	
	/**
	 * ico4 field in *Comparative → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: clients.items[].ico4
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	ico4: prismic.ImageField<never>;
	
	/**
	 * description4 field in *Comparative → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: clients.items[].description4
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	description4: prismic.KeyTextField;
	
	/**
	 * ico5 field in *Comparative → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: clients.items[].ico5
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	ico5: prismic.ImageField<never>;
	
	/**
	 * description5 field in *Comparative → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: clients.items[].description5
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	description5: prismic.KeyTextField;
	
	/**
	 * buttontext field in *Comparative → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: clients.items[].buttontext
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	buttontext: prismic.KeyTextField;
	
	/**
	 * buttonlink field in *Comparative → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: clients.items[].buttonlink
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	buttonlink: prismic.LinkField;
}

/**
 * Default variation for Comparative Slice
 *
 * - **API ID**: `default`
 * - **Description**: Clients
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ClientsSliceDefault = prismic.SharedSliceVariation<"default", Simplify<ClientsSliceDefaultPrimary>, Simplify<ClientsSliceDefaultItem>>;

/**
 * Slice variation for *Comparative*
 */
type ClientsSliceVariation = ClientsSliceDefault

/**
 * Comparative Shared Slice
 *
 * - **API ID**: `clients`
 * - **Description**: Clients
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ClientsSlice = prismic.SharedSlice<"clients", ClientsSliceVariation>;

/**
 * Primary content in *Contact → Default → Primary*
 */
export interface ContactSliceDefaultPrimary {
	/**
	 * title field in *Contact → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.RichTextField;
	
	/**
	 * subtitle field in *Contact → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.default.primary.subtitle
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	subtitle: prismic.RichTextField;
	
	/**
	 * name field in *Contact → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.default.primary.name
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	name: prismic.KeyTextField;
	
	/**
	 * email field in *Contact → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.default.primary.email
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	email: prismic.KeyTextField;
	
	/**
	 * message field in *Contact → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.default.primary.message
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	message: prismic.KeyTextField;
}

/**
 * Default variation for Contact Slice
 *
 * - **API ID**: `default`
 * - **Description**: Contact
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSliceDefault = prismic.SharedSliceVariation<"default", Simplify<ContactSliceDefaultPrimary>, never>;

/**
 * Primary content in *Contact → cotizarForm → Primary*
 */
export interface ContactSliceCotizarFormPrimary {
	/**
	 * subtitle field in *Contact → cotizarForm → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.cotizarForm.primary.subtitle
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	subtitle: prismic.RichTextField;
	
	/**
	 * name field in *Contact → cotizarForm → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.cotizarForm.primary.name
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	name: prismic.KeyTextField;
	
	/**
	 * email field in *Contact → cotizarForm → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.cotizarForm.primary.email
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	email: prismic.KeyTextField;
}

/**
 * cotizarForm variation for Contact Slice
 *
 * - **API ID**: `cotizarForm`
 * - **Description**: Contact
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSliceCotizarForm = prismic.SharedSliceVariation<"cotizarForm", Simplify<ContactSliceCotizarFormPrimary>, never>;

/**
 * Primary content in *Contact → enroll → Primary*
 */
export interface ContactSliceEnrollPrimary {
	/**
	 * title field in *Contact → enroll → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.enroll.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.RichTextField;
	
	/**
	 * subtitle field in *Contact → enroll → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.enroll.primary.subtitle
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	subtitle: prismic.RichTextField;
	
	/**
	 * name field in *Contact → enroll → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.enroll.primary.name
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	name: prismic.KeyTextField;
	
	/**
	 * birthday field in *Contact → enroll → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.enroll.primary.birthday
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	birthday: prismic.KeyTextField;
	
	/**
	 * address field in *Contact → enroll → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.enroll.primary.address
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	address: prismic.KeyTextField;
	
	/**
	 * phone field in *Contact → enroll → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.enroll.primary.phone
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	phone: prismic.KeyTextField;
	
	/**
	 * email field in *Contact → enroll → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.enroll.primary.email
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	email: prismic.KeyTextField;
	
	/**
	 * profession field in *Contact → enroll → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.enroll.primary.profession
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	profession: prismic.KeyTextField;
	
	/**
	 * studyinthearea field in *Contact → enroll → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.enroll.primary.studyinthearea
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	studyinthearea: prismic.KeyTextField;
	
	/**
	 * medicalhistory field in *Contact → enroll → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.enroll.primary.medicalhistory
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	medicalhistory: prismic.KeyTextField;
	
	/**
	 * emergencycontact field in *Contact → enroll → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.enroll.primary.emergencycontact
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	emergencycontact: prismic.KeyTextField;
}

/**
 * enroll variation for Contact Slice
 *
 * - **API ID**: `enroll`
 * - **Description**: Contact
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSliceEnroll = prismic.SharedSliceVariation<"enroll", Simplify<ContactSliceEnrollPrimary>, never>;

/**
 * Slice variation for *Contact*
 */
type ContactSliceVariation = ContactSliceDefault | ContactSliceCotizarForm | ContactSliceEnroll

/**
 * Contact Shared Slice
 *
 * - **API ID**: `contact`
 * - **Description**: Contact
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSlice = prismic.SharedSlice<"contact", ContactSliceVariation>;

/**
 * Primary content in *Graduate → Default → Primary*
 */
export interface GraduateSliceDefaultPrimary {
	/**
	 * Title field in *Graduate → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: This is where it all begins...
	 * - **API ID Path**: graduate.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;
}

/**
 * Primary content in *Graduate → Items*
 */
export interface GraduateSliceDefaultItem {
	/**
	 * image field in *Graduate → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: graduate.items[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
	
	/**
	 * name field in *Graduate → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: graduate.items[].name
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	name: prismic.RichTextField;
	
	/**
	 * country field in *Graduate → Items*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: CHILE
	 * - **API ID Path**: graduate.items[].country
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	country: prismic.SelectField<"CHILE" | "ESTADOS UNIDOS" | "COLOMBIA" | "ARGENTINA" | "PANAMA", "filled">;
	
	/**
	 * courses field in *Graduate → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: graduate.items[].courses
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	courses: prismic.KeyTextField;
}

/**
 * Default variation for Graduate Slice
 *
 * - **API ID**: `default`
 * - **Description**: Graduate
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GraduateSliceDefault = prismic.SharedSliceVariation<"default", Simplify<GraduateSliceDefaultPrimary>, Simplify<GraduateSliceDefaultItem>>;

/**
 * Slice variation for *Graduate*
 */
type GraduateSliceVariation = GraduateSliceDefault

/**
 * Graduate Shared Slice
 *
 * - **API ID**: `graduate`
 * - **Description**: Graduate
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GraduateSlice = prismic.SharedSlice<"graduate", GraduateSliceVariation>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
	/**
	 * invertedLayout field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: hero.default.primary.invertedlayout
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	invertedlayout: prismic.BooleanField;
	
	/**
	 * image field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
	
	/**
	 * description field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;
	
	/**
	 * buttonText field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.buttontext
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	buttontext: prismic.KeyTextField;
	
	/**
	 * buttonLink field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.buttonlink
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	buttonlink: prismic.LinkField;
	
	/**
	 * mobileImage field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.mobileimage
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	mobileimage: prismic.ImageField<never>;
	
	/**
	 * title field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.RichTextField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<"default", Simplify<HeroSliceDefaultPrimary>, never>;

/**
 * Primary content in *Hero → noButtonNoDescription → Primary*
 */
export interface HeroSliceNoButtonNoDescriptionPrimary {
	/**
	 * invertedLayout field in *Hero → noButtonNoDescription → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: hero.noButtonNoDescription.primary.invertedlayout
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	invertedlayout: prismic.BooleanField;
	
	/**
	 * image field in *Hero → noButtonNoDescription → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.noButtonNoDescription.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
	
	/**
	 * title field in *Hero → noButtonNoDescription → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.noButtonNoDescription.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.RichTextField;
	
	/**
	 * mobileImage field in *Hero → noButtonNoDescription → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.noButtonNoDescription.primary.mobileimage
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	mobileimage: prismic.ImageField<never>;
}

/**
 * noButtonNoDescription variation for Hero Slice
 *
 * - **API ID**: `noButtonNoDescription`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceNoButtonNoDescription = prismic.SharedSliceVariation<"noButtonNoDescription", Simplify<HeroSliceNoButtonNoDescriptionPrimary>, never>;

/**
 * Primary content in *Hero → noButton → Primary*
 */
export interface HeroSliceNoButtonPrimary {
	/**
	 * invertedLayout field in *Hero → noButton → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: hero.noButton.primary.invertedlayout
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	invertedlayout: prismic.BooleanField;
	
	/**
	 * image field in *Hero → noButton → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.noButton.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
	
	/**
	 * title field in *Hero → noButton → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.noButton.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.RichTextField;
	
	/**
	 * description field in *Hero → noButton → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.noButton.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;
	
	/**
	 * mobileImage field in *Hero → noButton → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.noButton.primary.mobileimage
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	mobileimage: prismic.ImageField<never>;
}

/**
 * noButton variation for Hero Slice
 *
 * - **API ID**: `noButton`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceNoButton = prismic.SharedSliceVariation<"noButton", Simplify<HeroSliceNoButtonPrimary>, never>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault | HeroSliceNoButtonNoDescription | HeroSliceNoButton

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *Ideas → Default → Primary*
 */
export interface IdeasSliceDefaultPrimary {
	/**
	 * subtittle field in *Ideas → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: ideas.default.primary.subtittle
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	subtittle: prismic.RichTextField;
	
	/**
	 * tittle field in *Ideas → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: ideas.default.primary.tittle
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	tittle: prismic.RichTextField;
	
	/**
	 * buttonText field in *Ideas → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: ideas.default.primary.buttontext
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	buttontext: prismic.KeyTextField;
	
	/**
	 * buttonLink field in *Ideas → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: ideas.default.primary.buttonlink
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	buttonlink: prismic.LinkField;
	
	/**
	 * bgColorInitial field in *Ideas → Default → Primary*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: ideas.default.primary.bgcolorInitial
	 * - **Documentation**: https://prismic.io/docs/field#color
	 */
	bgcolorInitial: prismic.ColorField;
	
	/**
	 * bgColorEnd field in *Ideas → Default → Primary*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: ideas.default.primary.bgcolorend
	 * - **Documentation**: https://prismic.io/docs/field#color
	 */
	bgcolorend: prismic.ColorField;
}

/**
 * Default variation for Ideas Slice
 *
 * - **API ID**: `default`
 * - **Description**: Ideas
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IdeasSliceDefault = prismic.SharedSliceVariation<"default", Simplify<IdeasSliceDefaultPrimary>, never>;

/**
 * Primary content in *Ideas → noButtonNobg → Primary*
 */
export interface IdeasSliceNoButtonNobgPrimary {
	/**
	 * subtittle field in *Ideas → noButtonNobg → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: ideas.noButtonNobg.primary.subtittle
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	subtittle: prismic.RichTextField;
	
	/**
	 * tittle field in *Ideas → noButtonNobg → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: ideas.noButtonNobg.primary.tittle
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	tittle: prismic.RichTextField;
}

/**
 * noButtonNobg variation for Ideas Slice
 *
 * - **API ID**: `noButtonNobg`
 * - **Description**: Ideas
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IdeasSliceNoButtonNobg = prismic.SharedSliceVariation<"noButtonNobg", Simplify<IdeasSliceNoButtonNobgPrimary>, never>;

/**
 * Primary content in *Ideas → noButton → Primary*
 */
export interface IdeasSliceNoButtonPrimary {
	/**
	 * subtittle field in *Ideas → noButton → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: ideas.noButton.primary.subtittle
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	subtittle: prismic.RichTextField;
	
	/**
	 * tittle field in *Ideas → noButton → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: ideas.noButton.primary.tittle
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	tittle: prismic.RichTextField;
	
	/**
	 * textbutton field in *Ideas → noButton → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: ideas.noButton.primary.textbutton
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	textbutton: prismic.KeyTextField;
	
	/**
	 * linkbutton field in *Ideas → noButton → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: ideas.noButton.primary.linkbutton
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	linkbutton: prismic.LinkField;
}

/**
 * noButton variation for Ideas Slice
 *
 * - **API ID**: `noButton`
 * - **Description**: Ideas
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IdeasSliceNoButton = prismic.SharedSliceVariation<"noButton", Simplify<IdeasSliceNoButtonPrimary>, never>;

/**
 * Slice variation for *Ideas*
 */
type IdeasSliceVariation = IdeasSliceDefault | IdeasSliceNoButtonNobg | IdeasSliceNoButton

/**
 * Ideas Shared Slice
 *
 * - **API ID**: `ideas`
 * - **Description**: Ideas
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IdeasSlice = prismic.SharedSlice<"ideas", IdeasSliceVariation>;

/**
 * Primary content in *LogoList → Default → Primary*
 */
export interface LogoListSliceDefaultPrimary {
	/**
	 * title field in *LogoList → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: logo_list.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;
	
	/**
	 * description field in *LogoList → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: logo_list.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;
}

/**
 * Primary content in *LogoList → Items*
 */
export interface LogoListSliceDefaultItem {
	/**
	 * logoImage field in *LogoList → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: logo_list.items[].logoImage
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	logoImage: prismic.ImageField<never>;
}

/**
 * Default variation for LogoList Slice
 *
 * - **API ID**: `default`
 * - **Description**: LogoList
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LogoListSliceDefault = prismic.SharedSliceVariation<"default", Simplify<LogoListSliceDefaultPrimary>, Simplify<LogoListSliceDefaultItem>>;

/**
 * Primary content in *LogoList → Items*
 */
export interface LogoListSliceOnlyLogosBgItem {
	/**
	 * logoImage field in *LogoList → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: logo_list.items[].logoImage
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	logoImage: prismic.ImageField<never>;
}

/**
 * onlyLogosBg variation for LogoList Slice
 *
 * - **API ID**: `onlyLogosBg`
 * - **Description**: LogoList
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LogoListSliceOnlyLogosBg = prismic.SharedSliceVariation<"onlyLogosBg", Record<string, never>, Simplify<LogoListSliceOnlyLogosBgItem>>;

/**
 * Primary content in *LogoList → buttonTitleDescription → Primary*
 */
export interface LogoListSliceButtonTitleDescriptionPrimary {
	/**
	 * title field in *LogoList → buttonTitleDescription → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: logo_list.buttonTitleDescription.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.RichTextField;
}

/**
 * Primary content in *LogoList → Items*
 */
export interface LogoListSliceButtonTitleDescriptionItem {
	/**
	 * logoImage field in *LogoList → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: logo_list.items[].logoImage
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	logoImage: prismic.ImageField<never>;
	
	/**
	 * subtitle field in *LogoList → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Titulo ...
	 * - **API ID Path**: logo_list.items[].subtitle
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	subtitle: prismic.RichTextField;
	
	/**
	 * description field in *LogoList → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Descripción ...
	 * - **API ID Path**: logo_list.items[].description
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	description: prismic.KeyTextField;
	
	/**
	 * buttonlink field in *LogoList → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: logo_list.items[].buttonlink
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	buttonlink: prismic.LinkField;
	
	/**
	 * buttontext field in *LogoList → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: logo_list.items[].buttontext
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	buttontext: prismic.KeyTextField;
}

/**
 * buttonTitleDescription variation for LogoList Slice
 *
 * - **API ID**: `buttonTitleDescription`
 * - **Description**: LogoList
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LogoListSliceButtonTitleDescription = prismic.SharedSliceVariation<"buttonTitleDescription", Simplify<LogoListSliceButtonTitleDescriptionPrimary>, Simplify<LogoListSliceButtonTitleDescriptionItem>>;

/**
 * Slice variation for *LogoList*
 */
type LogoListSliceVariation = LogoListSliceDefault | LogoListSliceOnlyLogosBg | LogoListSliceButtonTitleDescription

/**
 * LogoList Shared Slice
 *
 * - **API ID**: `logo_list`
 * - **Description**: LogoList
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LogoListSlice = prismic.SharedSlice<"logo_list", LogoListSliceVariation>;

/**
 * Primary content in *Metrics → Default → Primary*
 */
export interface MetricsSliceDefaultPrimary {
	/**
	 * title field in *Metrics → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: metrics.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;
}

/**
 * Primary content in *Metrics → Items*
 */
export interface MetricsSliceDefaultItem {
	/**
	 * contentText field in *Metrics → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: metrics.items[].contenttext
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	contenttext: prismic.KeyTextField;
	
	/**
	 * subtitle field in *Metrics → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: metrics.items[].subtitle
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	subtitle: prismic.KeyTextField;
}

/**
 * Default variation for Metrics Slice
 *
 * - **API ID**: `default`
 * - **Description**: Metrics
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MetricsSliceDefault = prismic.SharedSliceVariation<"default", Simplify<MetricsSliceDefaultPrimary>, Simplify<MetricsSliceDefaultItem>>;

/**
 * Primary content in *Metrics → noBackground → Primary*
 */
export interface MetricsSliceNoBackgroundPrimary {
	/**
	 * title field in *Metrics → noBackground → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: metrics.noBackground.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;
}

/**
 * Primary content in *Metrics → Items*
 */
export interface MetricsSliceNoBackgroundItem {
	/**
	 * contentText field in *Metrics → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: metrics.items[].contenttext
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	contenttext: prismic.KeyTextField;
	
	/**
	 * subtitle field in *Metrics → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: metrics.items[].subtitle
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	subtitle: prismic.KeyTextField;
}

/**
 * noBackground variation for Metrics Slice
 *
 * - **API ID**: `noBackground`
 * - **Description**: Metrics
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MetricsSliceNoBackground = prismic.SharedSliceVariation<"noBackground", Simplify<MetricsSliceNoBackgroundPrimary>, Simplify<MetricsSliceNoBackgroundItem>>;

/**
 * Slice variation for *Metrics*
 */
type MetricsSliceVariation = MetricsSliceDefault | MetricsSliceNoBackground

/**
 * Metrics Shared Slice
 *
 * - **API ID**: `metrics`
 * - **Description**: Metrics
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MetricsSlice = prismic.SharedSlice<"metrics", MetricsSliceVariation>;

/**
 * Primary content in *Projects → Default → Primary*
 */
export interface ProjectsSliceDefaultPrimary {
	/**
	 * imgSwapp field in *Projects → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: projects.default.primary.imgswapp
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	imgswapp: prismic.ImageField<never>;
	
	/**
	 * subtitle field in *Projects → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: projects.default.primary.subtitle
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	subtitle: prismic.KeyTextField;
	
	/**
	 * description field in *Projects → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: projects.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;
	
	/**
	 * title field in *Projects → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: projects.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;
}

/**
 * Default variation for Projects Slice
 *
 * - **API ID**: `default`
 * - **Description**: Projects
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectsSliceDefault = prismic.SharedSliceVariation<"default", Simplify<ProjectsSliceDefaultPrimary>, never>;

/**
 * Slice variation for *Projects*
 */
type ProjectsSliceVariation = ProjectsSliceDefault

/**
 * Projects Shared Slice
 *
 * - **API ID**: `projects`
 * - **Description**: Projects
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectsSlice = prismic.SharedSlice<"projects", ProjectsSliceVariation>;

/**
 * Primary content in *Reviews → Default → Primary*
 */
export interface ReviewsSliceDefaultPrimary {
	/**
	 * Title field in *Reviews → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: This is where it all begins...
	 * - **API ID Path**: reviews.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.RichTextField;
}

/**
 * Primary content in *Reviews → Items*
 */
export interface ReviewsSliceDefaultItem {
	/**
	 * image field in *Reviews → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: reviews.items[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
	
	/**
	 * name field in *Reviews → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: reviews.items[].name
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	name: prismic.RichTextField;
	
	/**
	 * numbersOfStars field in *Reviews → Items*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: *None*
	 * - **API ID Path**: reviews.items[].numbersofstars
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	numbersofstars: prismic.NumberField;
	
	/**
	 * recomendation field in *Reviews → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: reviews.items[].recomendation
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	recomendation: prismic.RichTextField;
	
	/**
	 * url field in *Reviews → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: Url External Review
	 * - **API ID Path**: reviews.items[].url
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	url: prismic.LinkField;
}

/**
 * Default variation for Reviews Slice
 *
 * - **API ID**: `default`
 * - **Description**: Reviews
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ReviewsSliceDefault = prismic.SharedSliceVariation<"default", Simplify<ReviewsSliceDefaultPrimary>, Simplify<ReviewsSliceDefaultItem>>;

/**
 * Slice variation for *Reviews*
 */
type ReviewsSliceVariation = ReviewsSliceDefault

/**
 * Reviews Shared Slice
 *
 * - **API ID**: `reviews`
 * - **Description**: Reviews
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ReviewsSlice = prismic.SharedSlice<"reviews", ReviewsSliceVariation>;

/**
 * Primary content in *Services → Default → Primary*
 */
export interface ServicesSliceDefaultPrimary {
	/**
	 * title field in *Services → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;
	
	/**
	 * description field in *Services → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;
	
	/**
	 * image field in *Services → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.default.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
	
	/**
	 * buttontext field in *Services → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.default.primary.buttontext
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	buttontext: prismic.KeyTextField;
}

/**
 * Primary content in *Services → Items*
 */
export interface ServicesSliceDefaultItem {
	/**
	 * imageList field in *Services → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.items[].imagelist
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	imagelist: prismic.ImageField<never>;
	
	/**
	 * titleList field in *Services → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.items[].titlelist
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	titlelist: prismic.KeyTextField;
	
	/**
	 * descriptionList field in *Services → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.items[].descriptionlist
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	descriptionlist: prismic.KeyTextField;
}

/**
 * Default variation for Services Slice
 *
 * - **API ID**: `default`
 * - **Description**: Services
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesSliceDefault = prismic.SharedSliceVariation<"default", Simplify<ServicesSliceDefaultPrimary>, Simplify<ServicesSliceDefaultItem>>;

/**
 * Primary content in *Services → noIconsNoButtons → Primary*
 */
export interface ServicesSliceNoIconsNoButtonsPrimary {
	/**
	 * title field in *Services → noIconsNoButtons → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.noIconsNoButtons.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;
	
	/**
	 * description field in *Services → noIconsNoButtons → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.noIconsNoButtons.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;
	
	/**
	 * image field in *Services → noIconsNoButtons → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.noIconsNoButtons.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
	
	/**
	 * buttontext field in *Services → noIconsNoButtons → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.noIconsNoButtons.primary.buttontext
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	buttontext: prismic.KeyTextField;
	
	/**
	 * buttonlink field in *Services → noIconsNoButtons → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.noIconsNoButtons.primary.buttonlink
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	buttonlink: prismic.LinkField;
}

/**
 * noIconsNoButtons variation for Services Slice
 *
 * - **API ID**: `noIconsNoButtons`
 * - **Description**: Services
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesSliceNoIconsNoButtons = prismic.SharedSliceVariation<"noIconsNoButtons", Simplify<ServicesSliceNoIconsNoButtonsPrimary>, never>;

/**
 * Primary content in *Services → noIcons → Primary*
 */
export interface ServicesSliceNoIconsPrimary {
	/**
	 * title field in *Services → noIcons → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.noIcons.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;
	
	/**
	 * description field in *Services → noIcons → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.noIcons.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;
	
	/**
	 * image field in *Services → noIcons → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.noIcons.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
	
	/**
	 * buttontext field in *Services → noIcons → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.noIcons.primary.buttontext
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	buttontext: prismic.KeyTextField;
}

/**
 * noIcons variation for Services Slice
 *
 * - **API ID**: `noIcons`
 * - **Description**: Services
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesSliceNoIcons = prismic.SharedSliceVariation<"noIcons", Simplify<ServicesSliceNoIconsPrimary>, never>;

/**
 * Primary content in *Services → imageText → Primary*
 */
export interface ServicesSliceImageTextPrimary {
	/**
	 * title field in *Services → imageText → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.imageText.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;
	
	/**
	 * image field in *Services → imageText → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.imageText.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
}

/**
 * imageText variation for Services Slice
 *
 * - **API ID**: `imageText`
 * - **Description**: Services
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesSliceImageText = prismic.SharedSliceVariation<"imageText", Simplify<ServicesSliceImageTextPrimary>, never>;

/**
 * Slice variation for *Services*
 */
type ServicesSliceVariation = ServicesSliceDefault | ServicesSliceNoIconsNoButtons | ServicesSliceNoIcons | ServicesSliceImageText

/**
 * Services Shared Slice
 *
 * - **API ID**: `services`
 * - **Description**: Services
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesSlice = prismic.SharedSlice<"services", ServicesSliceVariation>;

/**
 * Primary content in *Staff → Default → Primary*
 */
export interface StaffSliceDefaultPrimary {
	/**
	 * title field in *Staff → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: staff.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.RichTextField;
}

/**
 * Primary content in *Staff → Items*
 */
export interface StaffSliceDefaultItem {
	/**
	 * image field in *Staff → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: staff.items[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
	
	/**
	 * nametitle field in *Staff → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: staff.items[].nametitle
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	nametitle: prismic.KeyTextField;
	
	/**
	 * positiontitle field in *Staff → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: staff.items[].positiontitle
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	positiontitle: prismic.KeyTextField;
	
	/**
	 * linkedinlogo field in *Staff → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: staff.items[].linkedinlogo
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	linkedinlogo: prismic.ImageField<never>;
	
	/**
	 * profileurl field in *Staff → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: staff.items[].profileurl
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	profileurl: prismic.LinkField;
}

/**
 * Default variation for Staff Slice
 *
 * - **API ID**: `default`
 * - **Description**: Staff
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StaffSliceDefault = prismic.SharedSliceVariation<"default", Simplify<StaffSliceDefaultPrimary>, Simplify<StaffSliceDefaultItem>>;

/**
 * Slice variation for *Staff*
 */
type StaffSliceVariation = StaffSliceDefault

/**
 * Staff Shared Slice
 *
 * - **API ID**: `staff`
 * - **Description**: Staff
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StaffSlice = prismic.SharedSlice<"staff", StaffSliceVariation>;

declare module "@prismicio/client" {
	interface CreateClient {
		(repositoryNameOrEndpoint: string, options?: prismicClient.ClientConfig): prismicClient.Client<AllDocumentTypes>;
	}
	
	namespace Content {
		export type {
			FootermenuDocument,
			FootermenuDocumentData,
			FootermenuDocumentDataLinkgroupItem,
			FootermenuDocumentDataSocialmediagroupItem,
			HomepageDocument,
			HomepageDocumentData,
			HomepageDocumentDataSlicesSlice,
			MenutopDocument,
			MenutopDocumentData,
			MenutopDocumentDataMenulinksItem,
			PageDocument,
			PageDocumentData,
			PageDocumentDataSlicesSlice,
			AllDocumentTypes,
			CardListSlice,
			CardListSliceDefaultPrimary,
			CardListSliceDefaultItem,
			CardListSliceVariation,
			CardListSliceDefault,
			ClientsSlice,
			ClientsSliceDefaultPrimary,
			ClientsSliceDefaultItem,
			ClientsSliceVariation,
			ClientsSliceDefault,
			ContactSlice,
			ContactSliceDefaultPrimary,
			ContactSliceCotizarFormPrimary,
			ContactSliceEnrollPrimary,
			ContactSliceVariation,
			ContactSliceDefault,
			ContactSliceCotizarForm,
			ContactSliceEnroll,
			GraduateSlice,
			GraduateSliceDefaultPrimary,
			GraduateSliceDefaultItem,
			GraduateSliceVariation,
			GraduateSliceDefault,
			HeroSlice,
			HeroSliceDefaultPrimary,
			HeroSliceNoButtonNoDescriptionPrimary,
			HeroSliceNoButtonPrimary,
			HeroSliceVariation,
			HeroSliceDefault,
			HeroSliceNoButtonNoDescription,
			HeroSliceNoButton,
			IdeasSlice,
			IdeasSliceDefaultPrimary,
			IdeasSliceNoButtonNobgPrimary,
			IdeasSliceNoButtonPrimary,
			IdeasSliceVariation,
			IdeasSliceDefault,
			IdeasSliceNoButtonNobg,
			IdeasSliceNoButton,
			LogoListSlice,
			LogoListSliceDefaultPrimary,
			LogoListSliceDefaultItem,
			LogoListSliceOnlyLogosBgItem,
			LogoListSliceButtonTitleDescriptionPrimary,
			LogoListSliceButtonTitleDescriptionItem,
			LogoListSliceVariation,
			LogoListSliceDefault,
			LogoListSliceOnlyLogosBg,
			LogoListSliceButtonTitleDescription,
			MetricsSlice,
			MetricsSliceDefaultPrimary,
			MetricsSliceDefaultItem,
			MetricsSliceNoBackgroundPrimary,
			MetricsSliceNoBackgroundItem,
			MetricsSliceVariation,
			MetricsSliceDefault,
			MetricsSliceNoBackground,
			ProjectsSlice,
			ProjectsSliceDefaultPrimary,
			ProjectsSliceVariation,
			ProjectsSliceDefault,
			ReviewsSlice,
			ReviewsSliceDefaultPrimary,
			ReviewsSliceDefaultItem,
			ReviewsSliceVariation,
			ReviewsSliceDefault,
			ServicesSlice,
			ServicesSliceDefaultPrimary,
			ServicesSliceDefaultItem,
			ServicesSliceNoIconsNoButtonsPrimary,
			ServicesSliceNoIconsPrimary,
			ServicesSliceImageTextPrimary,
			ServicesSliceVariation,
			ServicesSliceDefault,
			ServicesSliceNoIconsNoButtons,
			ServicesSliceNoIcons,
			ServicesSliceImageText,
			StaffSlice,
			StaffSliceDefaultPrimary,
			StaffSliceDefaultItem,
			StaffSliceVariation,
			StaffSliceDefault
		}
	}
}