// Code generated by Slice Machine. DO NOT EDIT.

import CardList from './CardList';
import Comparative from './Comparative';
import Contact from './Contact';
import Graduate from './Graduate';
import Hero from './Hero';
import Ideas from './Ideas';
import Labels from './Labels';
import LogoList from './LogoList';
import Metrics from './Metrics';
import Projects from './Projects';
import RelatedContent from './RelatedContent';
import Reviews from './Reviews';
import Services from './Services';
import Staff from './Staff';

export {
	CardList,
	Comparative,
	Contact,
	Graduate,
	Hero,
	Ideas,
	Labels,
	LogoList,
	Metrics,
	Projects,
	RelatedContent,
	Reviews,
	Services,
	Staff,
};

export const components = {
	card_list: CardList,
	clients: Comparative,
	contact: Contact,
	graduate: Graduate,
	hero: Hero,
	ideas: Ideas,
	labels: Labels,
	logo_list: LogoList,
	metrics: Metrics,
	projects: Projects,
	related_content: RelatedContent,
	reviews: Reviews,
	services: Services,
	staff: Staff,
};
